### PR TITLE
Refactoring the kevlar workflow

### PR DESCRIPTION
**Pull request by standage**
This pull request is  work in progress. So far I have refactored the `kevlar find` procedure so that:

- it uses a `Counttable` instead of `Countgraph` (only choice using murmurhash3 for now)
- it reports only novel k-mers and the reads containing them
- it supports banding (f.k.a. "bitsplit")

All graph related stuff has been moved into the new `kevlar collect` procedure, which loads output from one or more independent `kevlar find` runs. This still uses `Countgraph`, since graph traversal functionality is needed to retrieve linear paths or assemble contigs.

The initial commits broke all of the automated tests, so these will need to be updated to match the new API.

### CODE REVIEW

**Comment by standage** [comment]
Still some kinks to work out, but overall I'm pleased with the state of the code. Waiting until we can rely on khmer master before merging.

**Comment by ctb** [comment]
what khmer PRs does this rely on, again?

**Comment by standage** [comment]
- `refactor/hashing2`
- `feature/consume_bitsplit`

All of my current testing is being done off of `research/banding_and_k32+`; this is a placeholder branch which is not intended to ever be merged, but simply keeps up-to-date with the other two listed above.

**Comment by standage** [comment]
The banding branch of khmer (`consume_bitsplit`) will not be making it into the imminent version 2.1 release it seems. Since kevlar has a way to go for a stable 1.0 release, I'll go ahead and merge this now.

**Pull request merged**
